[package]
name = "loco"
version = "0.0.0"
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
description = "Board support crate for loco"
categories = ["no-std"]
documentation = "https://docs.rs/loco"
repository = "https://github.com/dotcypress/loco"
authors = ["Vitaly Domnikov <oss@vitaly.codes>"]

[dependencies]
cortex-m-rt = "0.6.15"
panic-halt = "0.2.0"
stm32g0xx-hal = { version = "0.1.5", features = ["rt", "stm32g041"] }
kvs = { version = "0.0.3", optional = true }

[features]
store = ["dep:kvs"]
